export enum EAppStateActions {
  SET_IS_MOBILE = 'SET_IS_MOBILE',
  SHOW_ERR_MODAL = 'SHOW_ERR_MODAL',
  SHOW_AUTH_MODAL = 'SHOW_AUTH_MODAL',
  SHOW_INFO_MODAL = 'SHOW_INFO_MODAL',
  SHOW_CORNER_NOTIFIER = 'SHOW_CORNER_NOTIFIER',
}
